apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp2
parameters:
  fsType: ext4
  type: gp2
  encrypted: "${encrypted}"
volumeBindingMode: WaitForFirstConsumer
provisioner: "${provisioner}"
reclaimPolicy: Delete
volumeBindingMode: Immediate
