apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gpt2
parameters:
  fsType: ext4
  type: gpt2
  encrypted: "${encrypted}"
volumeBindingMode: WaitForFirstConsumer
provisioner: "${provisioner}"
reclaimPolicy: Retain
volumeBindingMode: Immediate
