---
# Source: cert-manager/templates/cainjector-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${release_name}-cainjector
  namespace: ${namespace}
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: ${release_name}
    app.kubernetes.io/component: "cainjector"
