---
# Source: cert-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ${release_name}
  namespace: ${namespace}
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: ${release_name}
    app.kubernetes.io/component: "controller"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9402
      targetPort: 9402
  selector:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: ${release_name}
    app.kubernetes.io/component: "controller"
