---
# Source: cert-manager/templates/webhook-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${release_name}-webhook
  namespace: ${namespace}
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: ${release_name}
    app.kubernetes.io/component: "webhook"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
      app.kubernetes.io/instance: ${release_name}
      app.kubernetes.io/component: "webhook"
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/name: webhook
        app.kubernetes.io/instance: ${release_name}
        app.kubernetes.io/component: "webhook"
      annotations:
        cni: ${cni}
    spec:
      serviceAccountName: ${release_name}-webhook
      # Note: Needed for EKS
      #hostNetwork: true
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-webhook:${image_version}"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          # Note: Change port from 10250 for KES hostNetwork
          - --secure-port=10250
          #- --secure-port=10254
          - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
          - --dynamic-serving-ca-secret-name=${release_name}-webhook-ca
          - --dynamic-serving-dns-names=${release_name}-webhook,${release_name}-webhook.${namespace},${release_name}-webhook.${namespace}.svc
          ports:
          - name: https
            containerPort: 10250
          livenessProbe:
            httpGet:
              path: /livez
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {}
